server:
  port: 85

spring:
  application:
    name: boot-shiro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    root: info
    com.spring.cloud.shiro.mapper: debug

