server:
  port: 83

spring:
  application:
    name: oauth2-examtool
  # redis
  redis:
    host: localhost
    port: 6379
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-demo?serverTimezone=GMT%2B8
    username: root
    password: root
  cloud:
    nacos:
      server-addr: localhost:8848

logging:
  level:
    com.spring.cloud.oauth2.examtool.mapper: debug

# MinIo文件服务器
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin